# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWSTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSMobileClient'
  pod 'AWSPinpoint'  

  target 'AWSTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AWSTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
